# DataCo Supply Chain - Data Cleaning and Preparation

Dataset source: https://www.kaggle.com/datasets/shashwatwork/dataco-smart-supply-chain-for-big-data-analysis

In [1]:
import pandas as pd

df_orig = pd.read_csv("DataCoSupplyChainDataset.csv",encoding="latin1")
df_orig.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [2]:
df_orig.shape

(180519, 53)

In [3]:
df = df_orig.copy()

In [4]:
df.columns.tolist()

['Type',
 'Days for shipping (real)',
 'Days for shipment (scheduled)',
 'Benefit per order',
 'Sales per customer',
 'Delivery Status',
 'Late_delivery_risk',
 'Category Id',
 'Category Name',
 'Customer City',
 'Customer Country',
 'Customer Email',
 'Customer Fname',
 'Customer Id',
 'Customer Lname',
 'Customer Password',
 'Customer Segment',
 'Customer State',
 'Customer Street',
 'Customer Zipcode',
 'Department Id',
 'Department Name',
 'Latitude',
 'Longitude',
 'Market',
 'Order City',
 'Order Country',
 'Order Customer Id',
 'order date (DateOrders)',
 'Order Id',
 'Order Item Cardprod Id',
 'Order Item Discount',
 'Order Item Discount Rate',
 'Order Item Id',
 'Order Item Product Price',
 'Order Item Profit Ratio',
 'Order Item Quantity',
 'Sales',
 'Order Item Total',
 'Order Profit Per Order',
 'Order Region',
 'Order State',
 'Order Status',
 'Order Zipcode',
 'Product Card Id',
 'Product Category Id',
 'Product Description',
 'Product Image',
 'Product Name',
 'Product Price',
 'Product Status',
 'shipping date (DateOrders)',
 'Shipping Mode']

In [5]:
# Renaming columns based on the official data description

columns_rename = {
    "Type": "transaction_type",

    # Shipping and delivery timing
    "Days for shipping (real)": "actual_shipping_days",
    "Days for shipment (scheduled)": "scheduled_shipping_days",
    "Delivery Status": "delivery_status",
    "Late_delivery_risk": "late_delivery_risk",

    # Financial metrics
    "Benefit per order": "profit_per_order",
    "Sales per customer": "sales_per_customer",

    # Product category
    "Category Id": "category_id",
    "Category Name": "category_name",

    # Customer information
    "Customer Id": "customer_id",
    "Customer Segment": "customer_segment",
    "Customer Fname": "customer_first_name",
    "Customer Lname": "customer_last_name",
    "Customer Email": "customer_email",
    "Customer Password": "customer_password",

    # Store location
    "Customer Street": "store_street",
    "Customer Zipcode": "store_zipcode",
    "Customer City": "store_city",
    "Customer Country": "store_country",
    "Customer State": "store_state",
    "Department Id": "store_department_id",
    "Department Name": "store_department_name",
    "Latitude": "store_latitude",
    "Longitude": "store_longitude",

    # Delivery destination geography
    "Market": "delivery_market",
    "Order Zipcode": "delivery_zipcode",
    "Order City": "delivery_city",
    "Order Country": "delivery_country",
    "Order Region": "delivery_region",
    "Order State": "delivery_state",
   
    # Order information
    "Order Id": "order_id",
    "Order Customer Id": "order_customer_id",
    "order date (DateOrders)": "order_date",
    "Order Status": "order_status",

    # Order item information
    "Order Item Id": "order_item_id",
    "Order Item Cardprod Id": "order_item_product_card_id",
    "Order Item Quantity": "order_item_quantity",
    "Order Item Product Price": "order_item_product_price",
    "Order Item Discount": "order_item_discount",
    "Order Item Discount Rate": "order_item_discount_rate",
    "Order Item Total": "order_item_total",
    "Order Item Profit Ratio": "order_item_profit_ratio",
    "Order Profit Per Order": "order_profit_per_order",

    # Sales
    "Sales": "sales",

    # Product information
    "Product Card Id": "product_card_id",
    "Product Category Id": "product_category_id",
    "Product Name": "product_name",
    "Product Price": "product_price",
    "Product Status": "product_stock_status",
    "Product Description": "product_description",
    "Product Image": "product_link",
    
    # Shipping
    "shipping date (DateOrders)": "shipping_date",
    "Shipping date (DateOrders)": "shipping_date",
    "Shipping Mode": "shipping_mode"
}

df = df.rename(columns=columns_rename)

columns_to_drop = [
    "customer_password",
    "product_link",
    "product_description"
]

df = df.drop(columns=columns_to_drop, errors="ignore")

print(df.shape)
df.head()

(180519, 50)

,transaction_type,actual_shipping_days,scheduled_shipping_days,profit_per_order,sales_per_customer,delivery_status,late_delivery_risk,category_id,category_name,store_city,...,delivery_state,order_status,delivery_zipcode,product_card_id,product_category_id,product_name,product_price,product_stock_status,shipping_date,shipping_mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,Java Occidental,COMPLETE,NaN,1360,73,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,Rajastán,PENDING,NaN,1360,73,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,Rajastán,CLOSED,NaN,1360,73,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,Queensland,COMPLETE,NaN,1360,73,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,Queensland,PENDING_PAYMENT,NaN,1360,73,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [6]:
# Group columns by business area to make the dataset structure clearer.

customer_cols = [
    "customer_id",
    "customer_segment",
    "customer_first_name",
    "customer_last_name",
    "customer_email",
    ]

order_cols = [
    "order_id",
    "order_customer_id",
    "order_date",
    "transaction_type",
    "order_status"
]

delivery_location_cols = [
    "delivery_city",
    "delivery_zipcode",
    "delivery_state",
    "delivery_region",
    "delivery_country",
    "delivery_market",
]

store_cols = [
    "store_department_id",
    "store_department_name",
    "store_street",
    "store_zipcode",
    "store_city",
    "store_state",
    "store_country",
    "store_latitude",
    "store_longitude"
]

product_cols = [
    "product_card_id",
    "product_name",
    "product_category_id",
    "product_price",
    "product_stock_status"
]

category_cols = [
    "category_id",
    "category_name"
]

order_item_cols = [
    "order_item_id",
    "order_item_quantity",
    "order_item_product_price",
    "order_item_discount",
    "order_item_discount_rate",
    "order_item_total",
    "order_item_profit_ratio",
    "order_item_product_card_id"
]

financial_cols = [
    "sales",
    "sales_per_customer",
    "profit_per_order",
    "order_profit_per_order"
]

shipping_cols = [
    "shipping_date",
    "shipping_mode",
    "scheduled_shipping_days",
    "actual_shipping_days",
    "delivery_status",
    "late_delivery_risk"
]

ordered_columns = (
    customer_cols
    + order_cols
    + delivery_location_cols
    + store_cols
    + product_cols
    + category_cols
    + order_item_cols
    + financial_cols
    + shipping_cols
)

# Check whether all expected columns are present and identify any extra columns.
missing_columns = [col for col in ordered_columns if col not in df.columns]
extra_columns = [col for col in df.columns if col not in ordered_columns]

print("Missing columns:", missing_columns)
print("Extra columns:", extra_columns)

df = df[[col for col in ordered_columns if col in df.columns] + extra_columns]

print(df.shape)
df.head()

Missing columns: []
Extra columns: []
(180519, 50)

,customer_id,customer_segment,customer_first_name,customer_last_name,customer_email,order_id,order_customer_id,order_date,transaction_type,order_status,...,sales,sales_per_customer,profit_per_order,order_profit_per_order,shipping_date,shipping_mode,scheduled_shipping_days,actual_shipping_days,delivery_status,late_delivery_risk
0,20755,Consumer,Cally,Holloway,XXXXXXXXX,77202,20755,1/31/2018 22:56,DEBIT,COMPLETE,...,327.75,314.640015,91.250000,91.250000,2/3/2018 22:56,Standard Class,4,3,Advance shipping,0
1,19492,Consumer,Irene,Luna,XXXXXXXXX,75939,19492,1/13/2018 12:27,TRANSFER,PENDING,...,327.75,311.359985,-249.089996,-249.089996,1/18/2018 12:27,Standard Class,4,5,Late delivery,1
2,19491,Consumer,Gillian,Maldonado,XXXXXXXXX,75938,19491,1/13/2018 12:06,CASH,CLOSED,...,327.75,309.720001,-247.779999,-247.779999,1/17/2018 12:06,Standard Class,4,4,Shipping on time,0
3,19490,Home Office,Tana,Tate,XXXXXXXXX,75937,19490,1/13/2018 11:45,DEBIT,COMPLETE,...,327.75,304.809998,22.860001,22.860001,1/16/2018 11:45,Standard Class,4,3,Advance shipping,0
4,19489,Corporate,Orli,Hendricks,XXXXXXXXX,75936,19489,1/13/2018 11:24,PAYMENT,PENDING_PAYMENT,...,327.75,298.250000,134.210007,134.210007,1/15/2018 11:24,Standard Class,4,2,Advance shipping,0

In [7]:
df.to_csv("dataco_clean_columns.csv", index=False)

In [8]:
# Check selected columns with missing values or low informational value.
cols_to_check = [
    "customer_email",
    "store_street",
    "delivery_zipcode",
    "product_stock_status"
]

existing_cols_to_check = [col for col in cols_to_check if col in df.columns]

check_cols = pd.DataFrame({
    "missing_values": df[existing_cols_to_check].isna().sum(),
    "unique_values": df[existing_cols_to_check].nunique(dropna=False)
})

check_cols

                      missing_values  unique_values
customer_email                     0              1
store_street                       0           7458
delivery_zipcode              155679            610
product_stock_status               0              1

In [9]:
# Drop columns that are not useful for the analysis or final dashboard.
columns_to_drop_2 = [
    "customer_email",
    "store_street",
    "delivery_zipcode",
    "product_stock_status"
   ]

df = df.drop(columns=columns_to_drop_2, errors="ignore")

print(df.shape)
df.head()

(180519, 46)

,customer_id,customer_segment,customer_first_name,customer_last_name,order_id,order_customer_id,order_date,transaction_type,order_status,delivery_city,...,sales,sales_per_customer,profit_per_order,order_profit_per_order,shipping_date,shipping_mode,scheduled_shipping_days,actual_shipping_days,delivery_status,late_delivery_risk
0,20755,Consumer,Cally,Holloway,77202,20755,1/31/2018 22:56,DEBIT,COMPLETE,Bekasi,...,327.75,314.640015,91.250000,91.250000,2/3/2018 22:56,Standard Class,4,3,Advance shipping,0
1,19492,Consumer,Irene,Luna,75939,19492,1/13/2018 12:27,TRANSFER,PENDING,Bikaner,...,327.75,311.359985,-249.089996,-249.089996,1/18/2018 12:27,Standard Class,4,5,Late delivery,1
2,19491,Consumer,Gillian,Maldonado,75938,19491,1/13/2018 12:06,CASH,CLOSED,Bikaner,...,327.75,309.720001,-247.779999,-247.779999,1/17/2018 12:06,Standard Class,4,4,Shipping on time,0
3,19490,Home Office,Tana,Tate,75937,19490,1/13/2018 11:45,DEBIT,COMPLETE,Townsville,...,327.75,304.809998,22.860001,22.860001,1/16/2018 11:45,Standard Class,4,3,Advance shipping,0
4,19489,Corporate,Orli,Hendricks,75936,19489,1/13/2018 11:24,PAYMENT,PENDING_PAYMENT,Townsville,...,327.75,298.250000,134.210007,134.210007,1/15/2018 11:24,Standard Class,4,2,Advance shipping,0

In [10]:
# Regroup columns after dropping unnecessary fields.
customer_cols = [
    "customer_id",
    "customer_segment",
    "customer_first_name",
    "customer_last_name"
]

delivery_location_cols = [
    "delivery_city",
    "delivery_state",
    "delivery_region",
    "delivery_country",
    "delivery_market"
]

store_cols = [
    "store_department_id",
    "store_department_name",
    "store_zipcode",
    "store_city",
    "store_state",
    "store_country",
    "store_latitude",
    "store_longitude"
]

product_cols = [
    "product_card_id",
    "product_name",
    "product_category_id",
    "product_price"
]

ordered_columns = (
    customer_cols
    + order_cols
    + delivery_location_cols
    + store_cols
    + product_cols
    + category_cols
    + order_item_cols
    + financial_cols
    + shipping_cols
)

missing_columns = [col for col in ordered_columns if col not in df.columns]
extra_columns = [col for col in df.columns if col not in ordered_columns]

print("Missing columns:", missing_columns)
print("Extra columns:", extra_columns)

df = df[[col for col in ordered_columns if col in df.columns] + extra_columns]

print(df.shape)
df.head()

Missing columns: []
Extra columns: []
(180519, 46)

,customer_id,customer_segment,customer_first_name,customer_last_name,order_id,order_customer_id,order_date,transaction_type,order_status,delivery_city,...,sales,sales_per_customer,profit_per_order,order_profit_per_order,shipping_date,shipping_mode,scheduled_shipping_days,actual_shipping_days,delivery_status,late_delivery_risk
0,20755,Consumer,Cally,Holloway,77202,20755,1/31/2018 22:56,DEBIT,COMPLETE,Bekasi,...,327.75,314.640015,91.250000,91.250000,2/3/2018 22:56,Standard Class,4,3,Advance shipping,0
1,19492,Consumer,Irene,Luna,75939,19492,1/13/2018 12:27,TRANSFER,PENDING,Bikaner,...,327.75,311.359985,-249.089996,-249.089996,1/18/2018 12:27,Standard Class,4,5,Late delivery,1
2,19491,Consumer,Gillian,Maldonado,75938,19491,1/13/2018 12:06,CASH,CLOSED,Bikaner,...,327.75,309.720001,-247.779999,-247.779999,1/17/2018 12:06,Standard Class,4,4,Shipping on time,0
3,19490,Home Office,Tana,Tate,75937,19490,1/13/2018 11:45,DEBIT,COMPLETE,Townsville,...,327.75,304.809998,22.860001,22.860001,1/16/2018 11:45,Standard Class,4,3,Advance shipping,0
4,19489,Corporate,Orli,Hendricks,75936,19489,1/13/2018 11:24,PAYMENT,PENDING_PAYMENT,Townsville,...,327.75,298.250000,134.210007,134.210007,1/15/2018 11:24,Standard Class,4,2,Advance shipping,0

In [11]:
df.to_csv("dataco_clean_columns_2.csv", index=False)

In [12]:
# Convert date columns to datetime format.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 46 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   customer_id                 180519 non-null  int64
 1   customer_segment            180519 non-null  object
 2   customer_first_name         180519 non-null  object
 3   customer_last_name          180511 non-null  object
 4   order_id                    180519 non-null  int64
 5   order_customer_id           180519 non-null  int64
 6   order_date                  180519 non-null  object
 7   transaction_type            180519 non-null  object
 8   order_status                180519 non-null  object
 9   delivery_city               180519 non-null  object
 10  delivery_state              180519 non-null  object
 11  delivery_region             180519 non-null  object
 12  delivery_country            180519 non-null  object
 13  delivery_market             180519 non-null  object
 14  store_department_id         180519 non-null  int64
 15  store_department_name       180519 non-null  object
 16  store_zipcode               180516 non-null  float64
 17  store_city                  180519 non-null  object
 18  store_state                 180519 non-null  object
 19  store_country               180519 non-null  object
 20  store_latitude              180519 non-null  float64
 21  store_longitude             180519 non-null  float64
 22  product_card_id             180519 non-null  int64
 23  product_name                180519 non-null  object
 24  product_category_id         180519 non-null  int64
 25  product_price               180519 non-null  float64
 26  category_id                 180519 non-null  int64
 27  category_name               180519 non-null  object
 28  order_item_id               180519 non-null  int64
 29  order_item_quantity         180519 non-null  int64
 30  order_item_product_price    180519 non-null  float64
 31  order_item_discount         180519 non-null  float64
 32  order_item_discount_rate    180519 non-null  float64
 33  order_item_total            180519 non-null  float64
 34  order_item_profit_ratio     180519 non-null  float64
 35  order_item_product_card_id  180519 non-null  int64
 36  sales                       180519 non-null  float64
 37  sales_per_customer          180519 non-null  float64
 38  profit_per_order            180519 non-null  float64
 39  order_profit_per_order      180519 non-null  float64
 40  shipping_date               180519 non-null  object
 41  shipping_mode               180519 non-null  object
 42  scheduled_shipping_days     180519 non-null  int64
 43  actual_shipping_days        180519 non-null  int64
 44  delivery_status             180519 non-null  object
 45  late_delivery_risk          180519 non-null  int64
dtypes: float64(13), int64(13), object(20)
memory usage: 63.4+ MB

In [13]:
#Convert date columns to datetime
df["order_date"] = pd.to_datetime(df["order_date"], errors="coerce")
df["shipping_date"] = pd.to_datetime(df["shipping_date"], errors="coerce")

df[["order_date", "shipping_date"]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 2 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   order_date     180519 non-null  datetime64[ns]
 1   shipping_date  180519 non-null  datetime64[ns]
dtypes: datetime64[ns](2)
memory usage: 2.8 MB

In [14]:
# Check for duplicated rows.
df.duplicated().sum()

np.int64(0)

In [15]:
# Check dataset granularity: order_item_id should be unique, while order_id can appear multiple times.
print(f"Is order_item_id unique?: {df["order_item_id"].is_unique}")
print(f"How many unique order_item_id are there?: {df['order_item_id'].nunique()}")
print(f"How many order_id are there?: {df["order_id"].nunique()}")

Is order_item_id unique?: True
How many unique order_item_id are there?: 180519
How many order_id are there?: 65752

In [16]:
# Check consistency between potential primary and foreign keys for the future data model.
print("order_item_product_card_id VS product_card_id:")
print((df['order_item_product_card_id'] == df['product_card_id']).value_counts())
print()
print("order_customer_id VS customer_id:")
print((df['order_customer_id'] == df['customer_id']).value_counts())
print()
print("product_category_id VS category_id:")
print((df['product_category_id'] == df['category_id']).value_counts())

# Some ID columns contain the same values row by row.
# They are kept because they support relationships between the future fact table
# and dimension tables in SQL and Power BI.

order_item_product_card_id VS product_card_id:
True    180519
Name: count, dtype: int64

order_customer_id VS customer_id:
True    180519
Name: count, dtype: int64

product_category_id VS category_id:
True    180519
Name: count, dtype: int64

In [17]:
# Convert store_zipcode from float to nullable integer format.

df["store_zipcode"] = df["store_zipcode"].astype("Int64")

df.to_csv("dataco_clean_columns_3.csv", index=False)

In [18]:
# Inspect records with missing store_zipcode values.
df[df["store_zipcode"].isna()][
    [
        "store_city",
        "store_state",
        "store_country",
        "store_latitude",
        "store_longitude"
    ]
]

      store_city store_state store_country  store_latitude  store_longitude
35704         CA       95758       EE. UU.       39.134159      -123.718552
46440         CA       95758       EE. UU.       38.408573      -121.449112
82511         CA       91732       EE. UU.       34.071892      -118.013886

In [19]:
# Check whether the missing zipcodes can be inferred from similar records in the dataset.
df[df["store_zipcode"]==95758][
    [
        "store_city",
        "store_state",
        "store_country",
        "store_latitude",
        "store_longitude",
        "store_zipcode"
    ]
]

,store_city,store_state,store_country,store_latitude,store_longitude,store_zipcode
1755,Elk Grove,CA,EE. UU.,38.415695,-121.418564,95758
2806,Elk Grove,CA,EE. UU.,38.415695,-121.418564,95758
4232,Elk Grove,CA,EE. UU.,38.408680,-121.479057,95758
10017,Elk Grove,CA,EE. UU.,38.415695,-121.418564,95758
17000,Elk Grove,CA,EE. UU.,38.415695,-121.418564,95758
...,...,...,...,...,...,...
169529,Elk Grove,CA,EE. UU.,38.409073,-121.419586,95758
169639,Elk Grove,CA,EE. UU.,38.409073,-121.419586,95758
169835,Elk Grove,CA,EE. UU.,38.409073,-121.419586,95758
169839,Elk Grove,CA,EE. UU.,38.409073,-121.419586,95758
172121,Elk Grove,CA,EE. UU.,38.415695,-121.418564,95758

In [20]:
# Verify that each selected zipcode is consistently associated with a single city.
print("Zipcode: 95758")
print(df[(df["store_zipcode"]==95758) & (df["store_state"]=="CA")]["store_city"].nunique())
print("City Name:")
print(df[(df["store_zipcode"]==95758) & (df["store_state"]=="CA")]["store_city"].unique())
print()
print("Zipcode: 91732")
print(df[(df["store_zipcode"]==91732) & (df["store_state"]=="CA")]["store_city"].nunique())
print("City Name:")
print(df[(df["store_zipcode"]==91732) & (df["store_state"]=="CA")]["store_city"].unique())

Zipcode: 95758
1
City Name:
['Elk Grove']

Zipcode: 91732
1
City Name:
['El Monte']

In [21]:
# Manual correction of shifted store location fields

df.loc[[35704, 46440], "store_city"] = "Elk Grove"
df.loc[[35704, 46440], "store_state"] = "CA"
df.loc[[35704, 46440], "store_zipcode"] = 95758

df.loc[82511, "store_city"] = "El Monte"   
df.loc[82511, "store_state"] = "CA"
df.loc[82511, "store_zipcode"] = 91732

df.loc[
    [35704, 46440, 82511],
    ["store_city", "store_state", "store_country", "store_zipcode", "store_latitude", "store_longitude"]
]

,store_city,store_state,store_country,store_zipcode,store_latitude,store_longitude
35704,Elk Grove,CA,EE. UU.,95758,39.134159,-123.718552
46440,Elk Grove,CA,EE. UU.,95758,38.408573,-121.449112
82511,El Monte,CA,EE. UU.,91732,34.071892,-118.013886

In [22]:
# Three records had shifted store location values:
# store_city contained the state, store_state contained the zipcode, and store_zipcode was missing.
# They were manually corrected using matching zipcode-city-state combinations already present in the dataset.

df["store_zipcode"].isna().sum()

np.int64(0)

In [23]:
# Standardize the store_country label.
print(f"Before: {df["store_country"].value_counts(dropna=False)}")

df["store_country"] = df["store_country"].replace({
    "EE. UU.": "USA"
})
print()
print(f"After: {df["store_country"].value_counts(dropna=False)}")

Before: store_country
EE. UU.        111146
Puerto Rico     69373
Name: count, dtype: int64

After: store_country
USA            111146
Puerto Rico     69373
Name: count, dtype: int64

In [24]:
# Remove leading and trailing spaces from text columns only

text_cols = df.select_dtypes(include="object").columns

for col in text_cols:
    df[col] = df[col].str.strip()

In [25]:
# Create a final data quality summary to review data types, missing values, and unique values.
data_quality_summary = pd.DataFrame({
    "dtype": df.dtypes,
    "missing_values": df.isna().sum(),
    "missing_pct": df.isna().mean() * 100,
    "unique_values": df.nunique()
})

data_quality_summary.sort_values("missing_pct", ascending=False).head(20)

,dtype,missing_values,missing_pct,unique_values
customer_last_name,object,8,0.004432,1109
customer_id,int64,0,0.000000,20652
order_item_product_card_id,int64,0,0.000000,118
category_id,int64,0,0.000000,51
category_name,object,0,0.000000,50
order_item_id,int64,0,0.000000,180519
order_item_quantity,int64,0,0.000000,5
order_item_product_price,float64,0,0.000000,75
order_item_discount,float64,0,0.000000,1017
order_item_discount_rate,float64,0,0.000000,18
order_item_total,float64,0,0.000000,2927
order_item_profit_ratio,float64,0,0.000000,162
sales,float64,0,0.000000,193
product_category_id,int64,0,0.000000,51
sales_per_customer,float64,0,0.000000,2927
profit_per_order,float64,0,0.000000,21998
order_profit_per_order,float64,0,0.000000,21998
shipping_date,datetime64[ns],0,0.000000,63701
shipping_mode,object,0,0.000000,4
scheduled_shipping_days,int64,0,0.000000,4

In [26]:
# Save the final cleaned dataset for SQL import and Power BI modeling.
df_clean = df.copy()
df_clean.to_csv("dataco_cleaned_final.csv", index=False)